apiVersion: v1
kind: Secret
metadata:
  name: private-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: helm
  url: https://ekpangmichael.github.io/helm-chart/charts
  password: <GITHUB TOKEN>
  username: <GITHUB TOKEN>