#helm upgrade --install argocd argo/argo-cd -n argocd -f values.yaml    
redis-ha:
  enabled: false

controller:
  replicas: 1

server:
  replicas: 1

repoServer:
  replicas: 1

applicationSet:
  replicas: 1

global:
  domain: argocd.michael-ekpang.com

configs:
  params:
    server.insecure: true
server:
  ingress:
    enabled: true
    ingressClassName: nginx


  

